### ISSUE TITLE
small readme enhancement: add image with nuget link to the readme

### ISSUE THREAD

**Issue by DevEddy** [Homegear/HomegearLib.NET#10]
`[![NuGet](https://img.shields.io/nuget/v/HomegearLib.NET.svg?maxAge=2592000)](https://www.nuget.org/packages/HomegearLib.NET/)`

Looks like: 

[![NuGet](https://img.shields.io/nuget/v/HomegearLib.NET.svg?maxAge=2592000)](https://www.nuget.org/packages/HomegearLib.NET/)

**Comment by hfedcba** [comment]
Done
