### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by Gonzo4** [Homegear/HomegearLib.NET#12]
Hi

is it possible to release this library under the MIT license?
... I would love to use this lib but I can't change the license of my whole project to GPL (from MIT)...

...Thanks ;)

**Comment by hfedcba** [comment]
The project is licensed under the LGPL for exactly that purpose. You can use the library in your program without restrictions. Your program can have any license - even commercial ones. So there shouldn't be any problems.

**Comment by Gonzo4** [comment]
Great news thanks ;)
...but the following license is the GPL V3.0, not the **L**GPL V3.0 or I'm wrong??
https://github.com/Homegear/HomegearLib.NET/blob/master/LICENSE

**Comment by hfedcba** [comment]
True, wrong license file. I replaced it now with the correct one. Thanks!

**Comment by Gonzo4** [comment]
Thanks :+1:
