### ISSUE TITLE
Pass Script to homegear

### ISSUE THREAD

**Issue by wbuh** [Homegear/HomegearLib.NET#2]
As I understand the Intellisense / Command-Completion HomegearLib.Homegear.RunScript only accepts a filename as parameter.
So the Script must already exist on the homegear machine.
If you connect remotely via HomegearLib.NET is there any other way to create such a script on the homegear machine from the remote system to run the script afterwards?
A nice feature would be to pass the complete script-code as a string to be executed by the homegear machine.

**Comment by hfedcba** [comment]
Yes, the script must preexist on the Homegear machine. I don't know if it's a good idea to add the possibility to remote execute scripts. It's a high security risk as you have no control over the script being executed. It would be easy to implement it though.

**Comment by wbuh** [comment]
Hi,
what about a config-parameter to allow or restrict "remoteScripting" on the homegear machine. In a second step a restriction to specific IPs as remote machines could limit the risc.

At the moment, I see the advantages: as long as some functions (like setInterface) are not implemented in the .NET dll, remotescripting could be used.
Otherwise endusers must copy such scripts to the raspi and assign correct file access before such helper-scripts could be used by a GUI for endusers - I don't know if beginners are able to to that.

**Comment by hfedcba** [comment]
The capability problem... Would you open a new issue in the Homegear project? Then I will add it ;-).

The .NET library is full featured though, so you can set the interface by assigning "Device.Interface" the new one!
