### ISSUE TITLE
ASP.NET Core support

### ISSUE THREAD

**Issue by tudoro** [Homegear/HomegearLib.NET#4]
Hi,

I would like to use this library, but in order to keep my application multi-platform I have to use ASP.NET Core. Could such support be added to this library?
I would be happy to contribute to this, but I'm not familiar with the internals of this library and what would need to be changed in order for it to work. I'm happy also with a few pointers on this and then I can try to implement this myself.

Cheers,
Tudor

**Comment by hfedcba** [comment]
Hey Tudor,

no idea how difficult it would be to port the library. I haven't worked with ASP.NET Core yet. I suppose that would mean using .NET Core.

I'm afraid currently I don't have time to look into that. But I would be happy to assist you.

Cheers,

Sathya
